### ISSUE TITLE
为什么从微信输入验证码之后，电脑浏览器刷新还是看不了

### ISSUE THREAD

**Issue by HomyeeKing** [shfshanyue/Daily-Question#359]

**Comment by shfshanyue** [comment]
具体你可以参考文章 [实现原理](https://github.com/shfshanyue/op-note/blob/master/blog-to-wechat.md)

简单一点方法可以在控制台输入以下语句

``` js
localStorage.token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1Nzc2MjI1MjEsImV4cCI6MTY3MjI5NTMyMX0.tB-CgK6aIo3whD-mAu3X37XT8q9v2bVXxG6llodznws'
```

**Comment by HomyeeKing** [comment]
> 猜测是未在三分钟内进行刷新验证，具体你可以参考文章 [实现原理](https://github.com/shfshanyue/op-note/blob/master/blog-to-wechat.md)
> 
> 简单一点方法可以在控制台输入以下语句
> 
> ```js
> localStorage.token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1Nzc2MjI1MjEsImV4cCI6MTY3MjI5NTMyMX0.tB-CgK6aIo3whD-mAu3X37XT8q9v2bVXxG6llodznws'
> ```
> 
> 如果还有问题，可以添加我的微信 `shanyue94`

刷新验证是刷新页面吧，不管了，已经手动添加token了
