### ISSUE TITLE
你的自动构建好像出问题了

### ISSUE THREAD

**Issue by iceytea** [shfshanyue/Daily-Question#395]
![image](https://user-images.githubusercontent.com/57755075/89703303-e4242400-d97b-11ea-9c29-a7a303eedf14.png)
这是说明

https://github.com/shfshanyue/Daily-Question/actions
这是自动构建记录

https://github.com/shfshanyue/Daily-Question/runs/959906262?check_suite_focus=true
这是最后一次错误信息

**Comment by shfshanyue** [comment]
其实我知道的，邮件不停报，只不过最近懒得改哈哈

**Comment by shfshanyue** [comment]
fixed，你把我的拖延症稍微挽救了些哈哈
