### ISSUE TITLE
引用仓库错了

### ISSUE THREAD

**Issue by zhengjiabo** [shfshanyue/Daily-Question#778]
[deploy/cra-docker.md](https://github.com/shfshanyue/Daily-Question/blob/ca6e814eaa21b9183455fa293397116851f283b8/deploy/cra-docker.md)

11行   PS: 本项目以 [cra-deploy]\(https://github.com/shfshanyue/simple-deploy)

PS: 本项目以 [cra-deploy]\(https://github.com/shfshanyue/cra-deploy)

**Comment by shfshanyue** [comment]
感谢感谢

**Comment by shfshanyue** [comment]
已修正
