### ISSUE TITLE
`<script type="module">`

### ISSUE THREAD

**Issue by chengjun0323** [shfshanyue/Daily-Question#782]
`<script type="module">`

- 模块自动使用严格模式
- 需要使用 defer 属性，模块会自动延迟加载

_Originally posted by @haotie1990 in https://github.com/shfshanyue/Daily-Question/issues/482#issuecomment-886452694_

**Comment by wolichuang** [comment]
1. 可以使用 js 最新语法引用外部脚本
2. 可以实现模块化
