### ISSUE TITLE
[feature request]面试题添加难度排序以及一键生成一份面试题的工具

### ISSUE THREAD

**Issue by kuige** [shfshanyue/Daily-Question#791]
希望所有题目都设置难度信息，并且可以按照难度排序

另外希望有这样一个工具，可以一键随机生成包含各种类型的面试题，html css js vue react 算法等，每种类型的题目随机生成，按照不同难度排序，不同难度等级的题目都随机来一些，也可以指定数量和类型，主要是方便面试官😂

**Comment by shfshanyue** [comment]
啊，有道理，好的好的。

**Comment by shfshanyue** [comment]
@kuige 算是添加上了，https://q.shanyue.tech/ai AI 智能出题，虽然他还是不太智能
